# Generated by Django 5.2.4 on 2025-08-26 12:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_sellerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='id_number',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(7)]),
        ),
    ]
