# Generated by Django 5.2.4 on 2025-08-26 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_sellerprofile_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='full_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
