# Generated by Django 5.2.4 on 2025-08-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userdetail_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
