# Generated by Django 5.2.5 on 2025-08-31 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userdetail_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
