# Generated by Django 5.2.5 on 2025-08-31 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_sellerprofile_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='last_name',
        ),
    ]
