# Generated by Django 5.2.5 on 2025-09-01 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_sellerprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
