# Generated by Django 5.2.5 on 2025-09-01 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_userdetail_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='email',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
