# Generated by Django 5.2.5 on 2025-09-02 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_userdetail_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='bio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
