# Generated by Django 5.2.4 on 2025-08-26 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_alter_sellerprofile_id_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductListings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='products/')),
                ('location', models.CharField(max_length=100)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.sellerprofile')),
            ],
        ),
    ]
