# Generated by Django 5.2.4 on 2025-08-26 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlistings',
            name='description',
            field=models.TextField(),
        ),
    ]
