# Generated by Django 5.2.5 on 2025-08-31 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_productlistings_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productlistings',
            old_name='posted_by',
            new_name='seller',
        ),
        migrations.AddField(
            model_name='productlistings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
